version: '3'
services:
  sonar:
    container_name: sonar-container
    image: sonarqube
    ports:
     - "9000:9000"
    volumes:
     - sonar_data:/opt/sonarqube/data
     - sonar_logs:/opt/sonarqube/logs
     - sonar_extensions:/opt/sonarqube/extensions

volumes:
  sonar_data:
  sonar_logs:
  sonar_extensions:
  