trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
    npm run test-ci   
    ls /coverage
    ls     
  displayName: 'npm install, unitTest and build'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'angular'
    targetPath: 'dist'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: angular2