trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
    npm run test-ci   
    ls /coverage
    ls     
  displayName: 'npm install, unitTest and build'

- task: SonarCloudPrepare@1
  displayName: 'Prepare analysis on Sonar'
  inputs:
    SonarCloud: 'sonar-cloud'
    scannerMode: 'CLI'
    organization: 'cacevedod'

- task: SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: sonarcloud-buildbreaker@2
  inputs:
    SonarCloud: 'sonar-cloud'
    organization: 'cacevedod'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist/pet-book'
    ArtifactName: pet-book